name: CI â€” Build & Push ACR (Watchtower mode)

on:
  push:
    branches: [ "main" ]

env:
  ACR_LOGIN: ${{ secrets.ACR_LOGIN }}
  IMG1: mqtt-kafka-bridge
  IMG2: kafka-redis-consumer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login no ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build+Push mqtt-kafka-bridge
        uses: docker/build-push-action@v6
        with:
          context: ./python-bridge
          push: true
          tags: |
            ${{ env.ACR_LOGIN }}/${{ env.IMG1 }}:latest
            ${{ env.ACR_LOGIN }}/${{ env.IMG1 }}:${{ github.sha }}

      - name: Build+Push kafka-redis-consumer
        uses: docker/build-push-action@v6
        with:
          context: ./kafka-redis-consumer
          push: true
          tags: |
            ${{ env.ACR_LOGIN }}/${{ env.IMG2 }}:latest
            ${{ env.ACR_LOGIN }}/${{ env.IMG2 }}:${{ github.sha }}
